# Generated by Django 5.0.4 on 2024-04-14 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmileblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='last_updated_short',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
