# Generated by Django 5.0.4 on 2024-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmileblog', '0005_post_author_full_name_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=255),
        ),
    ]
