# Generated by Django 5.0.4 on 2024-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmileblog', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures/'),
        ),
    ]
